spring.application.name=pension

server.port=${PORT}
booking.api.base=https://booking.ddnayo.com/booking-calendar-api
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5

# mySql
spring.datasource.url=jdbc:mysql://localhost:3306/nandapension
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

#mybatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml