spring.application.name=pension

server.port=${PORT:8082}
booking.api.base=https://booking.ddnayo.com/booking-calendar-api
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5

