spring.application.name=pension

server.port=${PORT:8082}
booking.api.base=https://booking.ddnayo.com/booking-calendar-api
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5

# MariaDB
spring.datasource.url=jdbc:mariadb://192.168.0.84:3306/ndpension
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Da317802!!

#mybatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml

#log
logging.level.root = info
logging.level.jdbc.sqlonly=off
logging.level.jdbc.sqltiming=info
logging.level.jdbc.resultsettable=info
logging.level.jdbc.audit=off
logging.level.jdbc.resultset=off
logging.level.jdbc.connection=off